// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kovbzsgudjsqdtzzaqud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdmJ6c2d1ZGpzcWR0enphcXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NTExNTYsImV4cCI6MjA3NjAyNzE1Nn0.h6VuA4G4E7_D9KRoXFKdNaF3jRwg-M_y0gTz04L8OOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});